preparing for fw repo to use
uwrobotics/uwrt_mars_rover_hw_bridge pull request #3
Opened 2020-06-24 00:25 UTC by younesr1

2020-06-25 04:36 UTC, wmmc88 requested changes

2020-06-25 04:36 UTC, wmmc88 commented on config/hw_bridge.h
> +            struct __attribute__ ((__packed__)) payload_st{
Why not typedef it?

2020-06-26 22:43 UTC, younesr1 commented on config/hw_bridge.h
> +            struct __attribute__ ((__packed__)) payload_st{
hmm do you mean do typedef struct __attribute__((__packed__)) packed_struct in the header?

2020-06-26 22:49 UTC, wmmc88 commented on config/hw_bridge.h
> +            struct __attribute__ ((__packed__)) payload_st{
Typedef before and removed the name after the attribute and put it after the closing brace of the struct def. It's so u dont have to write struct everywhere

2020-06-27 20:02 UTC, younesr1 commented on config/hw_bridge.h
> +            struct __attribute__ ((__packed__)) payload_st{
im pretty sure that's just a C thing. In cpp I can do the following:
struct younes{int a};
younes myObject;
this means I dont actually have to write struct everywhere, kinda like a class.

2020-06-27 22:59 UTC, wmmc88 commented on config/hw_bridge.h
> +            struct __attribute__ ((__packed__)) payload_st{
https://stackoverflow.com/a/1675446

2020-06-27 23:00 UTC, wmmc88 commented on config/hw_bridge.h
> +            struct __attribute__ ((__packed__)) payload_st{
It changes search rules. Which means u should still do the typedef to prevent the struct from getting overridden by a function or another class etc.

2020-07-01 16:55 UTC, wmmc88 commented
Is this ready?

2020-07-09 00:51 UTC, wmmc88 approved these changes
lgtm

2020-07-09 02:46 UTC, jetkov submitted a review, later dismissed
👍

2020-07-09 22:02 UTC, younesr1 commented
This is a protected branch. I cannot merge

2020-07-09 22:04 UTC, wmmc88 commented
Oops forgot. Its cuz theres no ci implemented yet

2020-07-09 22:04 UTC, merged